package com.ingokodba.morsecode

import android.provider.Settings.Global.getString
import android.widget.TextView
import com.ingokodba.morsecode.models.Postavke

enum class MorseCodeServiceMenus {
    MENU_MAIN,
    MENU_CHOOSE_CONTACTS,
    MENU_CONTACT_CHAT,
    MENU_READ_FROM_FILES,
    MENU_CHOOSE_FILE,
    MENU_SEARCH_IN_FILE,
    MENU_SEARCH_INTERNET,
    MENU_NAVIGATE_INTERNET
}

enum class MorseCodeServiceCommands {
    MAIN,
    CONTACTS,
    CONTACTS_NEXT,
    CONTACTS_PREVIOUS,
    CONTACTS_CHOOSE,
    CHAT_LAST_MESSAGE,
    CHAT_PREVIOUS,CHAT_NEXT,
    CHAT_SEND_NEW_MESSAGE,
    FILES,
    FILES_PICKER,
    FILES_CHOOSE_NEXT,
    FILES_CHOOSE_PREVIOUS,
    FILES_OPEN,
    FILES_SEARCH,
    FILES_SEARCH_NEXT,
    FILES_SEARCH_PREVIOUS,
    FILES_NEW,
    FILES_SAVE,
    FILES_WRITE,
    FILES_NEXT_LINE,
    FILES_PREVIOUS_LINE,
    INTERNET,
    INTERNET_SWITCH_ENGINE,
    INTERNET_FEELING_LUCKY,
    INTERNET_SEARCH,
    INTERNET_SEARCH_NEXT,
    INTERNET_SEARCH_PREVIOUS,
    INTERNET_SEARCH_SKIP_SENTENCE,
    GO_BACK,
    REPEAT
}

class MorseCodeServiceCommandLabels {

}
